import { DM_Sans , Playfair_Display ,  } from "next/font/google";
import "./globals.css";

const playfair_display = Playfair_Display({
  // variable: "--font-geist-sans",
  weight: ['400', '500' , '700', '600' , '800' , '900'],
  subsets: ["latin", 'cyrillic'],
  display: 'swap',
  style: 'normal'
});

const dm_sans = DM_Sans({
  // variable: "--font-geist-mono",
  weight: ['100', '200' , '300' , '400' , '500' , '600' , '700' , '800' , '900'],
  subsets: ["latin"],
  display: 'swap',
  style: 'normal'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      className={`${playfair_display.className} ${dm_sans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
